name: publish-docker

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta_jupyter
      uses: docker/metadata-action@v5.3.0
      with:
        images: glenn032787/scRNA-python

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        context: .
        push: true
        tags: ${{ steps.meta_jupyter.outputs.tags }}
        labels: ${{ steps.meta_jupyter.outputs.labels }}

